version: '3'

services:
  api:
    container_name: weightlifter-api 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: nodemon -L src/index.ts 
    depends_on:
      - db
  db:
    container_name: weightlifter-api-db
    image: mysql:5.7.24
    restart: always
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./data/sql:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

